/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */
/* auto-generated by NAPI-RS */

// @ts-expect-error
const node = __non_webpack_require__("../../../napi.darwin-arm64.node"); // use relative path from .next/server/app

console.log(node.sum(1, 2));

export const { sum } = node;
