/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */
const node = __non_webpack_require__("../../../napi.darwin-arm64.node"); // use relative path from .next/server/app

export const { asyncSum  } = node;
